### ISSUE TITLE
Thanks for the code!

### ISSUE THREAD

**Issue by Klortho** [cwi-swat/non-layered-tidy-trees#1]
Hi, I doubt anyone is watching this repo, but just in case, I just wanted to let you know I was able to use this code to create a plugin for D3, [here](https://github.com/klortho/d3-flextree).

Thanks!

**Comment by atzeus** [comment]
Cheers! Great that this algorithm found a user :) Will this go in the main D3 branch?

**Comment by Klortho** [comment]
I hope so, but that's entirely up to @mbostock. Meanwhile, I will be using it for my dtd-diagram project.
